services:
  apigateway:
    build:
      context: .  
      dockerfile: ApiGateway/Dockerfile
    image: apigateway
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - StorageServiceUrl=http://filestorageservice:8081
      - AnalysisServiceUrl=http://fileanalysisservice:8082

  filestorageservice:
    build:
      context: . 
      dockerfile: FileStorageService/Dockerfile
    image: filestorageservice
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
      - StoragePath=/app/data
    volumes:
      - ./storage_data:/app/data

  fileanalysisservice:
    build:
      context: .
      dockerfile: FileAnalysisService/Dockerfile
    image: fileanalysisservice
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_HTTP_PORTS=8082
